name: Lsd ka blog
title: Lsd's Blog | All about threat intel
description: Info about threat intel by
  Arav Tripathi
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: lsd@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
